### ISSUE TITLE
cannot fetch data when getting into the details page of one collection after setting the data range in the NFT garden

### ISSUE THREAD

**Issue by Moehringen** [web3go-xyz/portal-ui#7]
1. in the overview page of NFT garden, select one date range, for example:   from  2022.1.25 00:00:00 to 2022. 1.26 23:59:59. then click ok

2.select any collection and routed to the details page, the four chars are loading but without result

**Comment by happyJ2024** [comment]
field lack from query api.
fixed the issues with add collection_id
